.PHONY: install up down migrate test check seed

install:
	npm install

up:
	docker compose up -d

down:
	docker compose down

migrate:
	npm run migrate

seed:
	npm run seed

test:
	npm run test

check:
	npm run check
